# Setup
title:               Pincette1223
tagline:             '개발자를 꿈꾸는 핀셋의 개발일지'
description:         '핀셋의 깃허브 블로그입니다!'
url:                 https://pincette1223.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Pincette1223
  email:             vlstpt812@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
